#Configuration not fully implemented!
#I'd add the sql server to the docker compose
#also trying to have som automatic initial setup for auto creating DB and running the init.sql
services:
  royallibrary:
    image: royallibrary
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
